[package]
name = "rust_zombie"
version = "0.1.0"
authors = ["MarcuIsCode"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3.0"